const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../../.env') });
require('dotenv').config({ path: path.join(__dirname, '../.env.fetcher') });

const STRAPI_URL = process.env.STRAPI_URL || 'http://127.0.0.1:1337';
const API_TOKEN = process.env.STRAPI_API_TOKEN;

const updates = [
    // === TECHNOLOGY ===
    { documentId: "kg4kytf0qovbgxcgx82jq0hf", content: "Oracle has carried out significant job cuts, with an estimated 10,000 employees losing their positions. The company cited its increasing use of AI tools that enable smaller engineering teams to deliver more, while investing heavily in AI infrastructure including the $500 billion Stargate initiative." },
    { documentId: "nwajddykbfjx8nsephwd9hqb", content: "Kris Jenner has become an unexpected viral sensation on Chinese social media platforms like Weibo and RedNote, where hundreds of thousands of users are sharing her image as a symbol of luck and fortune. The trend stems from Chinese admiration for her reputation as a hardworking businesswoman." },
    { documentId: "ra7xrn9qp3n499qpv7x5fdr9", content: "Mainland Chinese tech companies are increasingly using Hong Kong as a springboard for international expansion, listing on its stock exchange and testing products there. Geopolitical tensions with the US and Europe have made direct overseas expansion harder, pushing firms to use Hong Kong as a trusted intermediary." },
    { documentId: "shjd253d43xuiwabhho1i4on", content: "A software defect at Lloyds Banking Group exposed the transaction data of up to 447,936 customers, including account details and national insurance numbers. The bank has paid £139,000 in goodwill payments to around 3,625 affected customers and is cooperating with financial regulators." },
    { documentId: "ybqtiwmmdm5rk7yibldsjw0l", content: "A federal judge sided with AI company Anthropic, blocking the Pentagon's attempt to ban all government agencies from using its tools. The judge called it 'classic First Amendment retaliation' after the company raised concerns about its technology being used for mass surveillance and autonomous weapons." },
    { documentId: "h4mcacoifv740vl581ehe8co", content: "The UK's Competition and Markets Authority is investigating Just Eat, Autotrader, and other firms over fake and misleading online reviews. The probe examines whether these companies have adequate systems to detect and remove fraudulent reviews on their platforms." },
    { documentId: "ntxa6ze5qx9bc7f081v0mdwu", content: "A US judge dismissed Elon Musk's lawsuit alleging that major advertisers including Unilever, Mars, and Orsted illegally boycotted X (formerly Twitter). The judge found insufficient evidence that the companies conspired rather than independently making business decisions about advertising." },
    { documentId: "jc8bomn8ikn3ialhgi52lks8", content: "Australia's online safety watchdog has urged social media companies to do more to enforce the country's under-16 ban on social media. The regulator found that platforms are not implementing adequate age verification measures to comply with the landmark legislation." },
    { documentId: "logfbx98fopm9qv7ji6h12nn", content: "Tech CEOs including Mark Zuckerberg and Jack Dorsey are increasingly citing AI as the reason for mass layoffs, claiming AI tools allow fewer employees to do more work. However, the tech industry has been conducting annual mass layoffs for years before AI became the stated justification." },
    { documentId: "nshigi4tx8ly1h5ozoi1y26z", content: "Sony is raising the PlayStation 5 price by £90 in the UK and $100 in the US, citing global economic pressures including tariffs, currency fluctuations, and rising manufacturing costs. The price hike is one of the most dramatic in recent console gaming history." },
    { documentId: "ai5syvgvzzbqnen2gsupj1e7", content: "A practical guide to identifying fake news on social media, covering techniques like checking the source URL, reading beyond headlines, verifying authors' credentials, using reverse image search, and consulting fact-checking websites before sharing stories." },
    { documentId: "lve7enkc2vp9mm443skqppzu", content: "An autonomous electric race car called DevBot completed a successful street track debut at the Formula E Marrakech ePrix in Morocco. The driverless vehicle is part of the planned Roborace series where autonomous cars will compete alongside Formula E events." },
    { documentId: "sz8h81lb7faygocz9ernhkk9", content: "NASA astronaut Shane Kimbrough successfully cast his ballot in the presidential election from the International Space Station, using a secure electronic voting system that allows astronauts to participate in elections from orbit." },
    { documentId: "wxi2wee5flle518a7vj0xks2", content: "Astronauts on the International Space Station can temporarily gain 2 inches in height due to spinal elongation in microgravity, but suffer significant muscle loss and back pain. Researchers are developing exercise countermeasures to help mitigate these effects during long-duration missions." },
    { documentId: "sueews16dsvcgq42mmfkf362", content: "A comprehensive guide for parents on virtual reality headsets for children, covering options from inexpensive Google Cardboard to premium PlayStation VR, with advice on age-appropriate content, safety considerations, and potential side effects like motion sickness." },
    // Technology - TechCrunch
    { documentId: "u99w1sg5fd5qwjn8xy9kapnw", content: "Senator Ed Markey asked seven major autonomous vehicle companies how often their vehicles need remote human intervention, but most refused to disclose specific figures. The lack of transparency raises concerns about the true readiness of self-driving technology for widespread deployment." },
    { documentId: "upyoj15u5mpzuna384zcud8a", content: "OpenAI closed a $122 billion funding round at an $852 billion valuation, including $3 billion from retail investors. The massive raise will fund AI chip purchases and data center buildouts as the company prepares for an expected IPO." },
    { documentId: "gr3g0kbnxna155k1mjp60oe3", content: "AI seed-stage startups are commanding significantly higher valuations than just two years ago, with typical rounds now reaching $25 million post-money or higher. The trend reflects intense investor appetite for AI companies, though some warn it creates pressure to justify inflated early-stage prices." },
    { documentId: "p3q62kr7hayeec5rujs72zw5", content: "Yupp, a crowdsourced AI model-picking platform, is shutting down less than a year after launching despite raising $33 million from prominent investor a16z crypto's Chris Dixon. The closure highlights the challenges of building viable AI businesses even with significant funding." },
    { documentId: "y8c5pe85v4u83j0mnxw83zxj", content: "Meta lost two consecutive lawsuits regarding child safety — one in New Mexico and a jury verdict in Los Angeles — marking the first times a court held the company liable for endangering children on its platforms. The rulings could set precedent for future social media safety litigation." },
    { documentId: "wp8uhneisy7lzmh43vx7fqse", content: "TikTok has added a hidden emoji game accessible through DMs where players bounce across alligators while avoiding skeleton versions. The secret game can be activated by sending specific emojis in direct messages." },
    { documentId: "dpe1ze4yq914ymhu07rt7twe", content: "Sweden-based caller ID app Truecaller has reached 500 million monthly active users globally, with India being its largest market at over 350 million users. The company has also crossed 150 million users outside India." },
    { documentId: "ojatbrc71hcztn4fvc7fhjxl", content: "Amazon's Alexa+ now supports conversational food ordering from Uber Eats and Grubhub, allowing users to browse menus, customize orders, and check out using natural language — similar to placing an order at a drive-thru." },
    { documentId: "n67qxwbtz12tj9cs8481s829", content: "Rec Room, once valued at $3.5 billion as a social gaming platform, announced it will shut down on June 1. The closure marks the end of a once-promising virtual world platform that attracted millions of users creating and exploring user-generated content." },
    { documentId: "s5g3d89blx2y5xub96jwko9v", content: "Whoop, the fitness tracking wearable company, closed a $575 million Series G round at a $10.1 billion valuation — nearly triple its previous $3.6 billion valuation. The funding brings together sovereign wealth funds and major health institutions." },
    // === BUSINESS ===
    { documentId: "b4p97mo893zg1ekk7r4h0ayn", content: "US retail spending fell 1% in March, steeper than the expected 0.4% decline, as consumers pulled back amid recession fears following the banking crisis. The weakness was partially attributed to delayed tax returns and lingering economic uncertainty." },
    { documentId: "jfp9adgpbfzh3s9dyg887vw3", content: "The collapse of Silicon Valley Bank has reignited concerns about financial disparities facing entrepreneurs of color. SVB was known for servicing underrepresented communities, and its failure has limited already scarce funding options for minority startup founders." },
    { documentId: "myq5rexc6q4nvosf4n082jdy", content: "A last-minute tax filing guide for the millions who haven't yet submitted returns before the April 18 deadline. Key tips include checking for disaster area extensions, maximizing deductions, and understanding free filing options available through the IRS." },
    { documentId: "yav0f0dp4o0rci6xjiqateno", content: "The Dominion Voting Systems $1.6 billion defamation trial against Fox News is about to begin in Delaware, with jury selection completed. The case will examine whether Fox knowingly broadcast false claims about election fraud, potentially becoming the biggest media defamation trial in history." },
    // CNBC Business
    { documentId: "mnsybyqx3twxdmjafxhecf4a", content: "Nike shares dropped 9% after the company issued a weaker-than-expected sales outlook despite beating quarterly earnings estimates. Revenue in Greater China fell but still beat estimates, while the company warned of an expected 20% sales decline in the Chinese market." },
    { documentId: "c73xjfebhk3xe5d0b0smu3jw", content: "Retired NFL quarterback Tom Brady explains his pivot to endorsing junk food brands like Pizza Hut and Dunkin' after maintaining a famously strict diet during his playing career, saying he believes in 'moderation in all things' and chooses partnerships driven by good scripts." },
    { documentId: "jeqqbqdn8t9fboryo8k7qlbk", content: "Mercedes-Benz USA CEO Adam Chamberlain said 2026 is more challenging than expected due to elevated auto loan rates and rising gas prices. Mercedes is investing $4 billion in its Alabama plant through 2030 to increase domestic production." },
    { documentId: "h1q2xe0majatnksc888w0e6m", content: "Amazon MGM's 'Project Hail Mary' has surpassed $300 million globally, becoming the studio's highest-grossing film. The sci-fi film showed strong holding power with only a 32% drop from its opening weekend." },
    { documentId: "pxx1nk2r55pzjcrxtn9xbems", content: "Spice giant McCormick is acquiring Unilever's food business, including Hellmann's mayo, in a deal valued at nearly $45 billion. Unilever plans to refocus on its faster-growing personal-care business." },
    { documentId: "npgq8xlt8vj0tp750j3kff7w", content: "Eli Lilly will pay up to $7.8 billion to acquire Centessa Pharmaceuticals, which is developing experimental treatments for narcolepsy and excessive drowsiness. The deal continues Lilly's strategy of using its GLP-1 drug windfall to make strategic acquisitions." },
    { documentId: "i4lf8sg1hh7rlvce0tfla4ww", content: "Opendoor is acquiring part of Doma, a property tech company that uses AI to streamline real estate closings, to help lower mortgage refinance costs. About 85 Doma employees will join Opendoor following the acquisition." },
    { documentId: "yf7wanm1f9npnwgtz203seex", content: "JetBlue Airways is raising checked bag fees by $4 to $9 as fuel prices surge due to the Middle East conflict. Airfare costs have climbed across routes worldwide driven by soaring oil prices." },
    { documentId: "gllg0drbeu3fn2gce2f1rlkt", content: "Novo Nordisk launched multi-month subscription plans for its Wegovy obesity drug, offering three-, six-, or twelve-month options to provide lower, predictable pricing for cash-paying patients as it competes with Eli Lilly in the weight-loss drug market." },
    { documentId: "v7gq7febizqlev7skp96e06e", content: "Delta Air Lines signed an agreement with Amazon's Project Leo for in-flight Wi-Fi starting in 2028, initially covering 500 aircraft. American Airlines is also considering Amazon Leo for its own in-flight entertainment upgrade." },
    // === SPORTS ===
    { documentId: "cv89adz8b6fnfxhtvzjiwrwg", content: "Bosnia and Herzegovina eliminated four-time champions Italy from the World Cup 2026 qualifiers, winning 4-1 on penalties after a 1-1 draw in extra time. Italy, reduced to 10 men in the first half, will miss a third consecutive World Cup." },
    { documentId: "ahcm6nbq4h89lwgnima6o7t5", content: "Fifteen-time major champion Tiger Woods pleaded not guilty to misdemeanor DUI with property damage charges stemming from a car crash. Court documents show opioid pain medications were found at the scene." },
    { documentId: "yj6pc7lzhx37y1vtg5y6dm2e", content: "NBA coaches, executives, and scouts outline six potential free agency destinations for LeBron James, analyzing the fit, salary implications, and championship potential of each scenario as the Lakers star considers his future." },
    { documentId: "dzvm5kq4mfy7ywkg6hcu7svh", content: "NFL owners approved two major changes to the replay review system designed to speed up games and improve officiating accuracy. The changes represent some of the most significant replay rule modifications in recent years." },
    { documentId: "ot7wem3bdm8eduexshf7xg74", content: "Four-time champions Italy missed out on a third consecutive World Cup, falling to Bosnia and Herzegovina in a penalty shootout in their European qualifying playoff final." },
    { documentId: "pyo5jork5xu73je3r33epu0v", content: "Ohio State coach Ryan Day compared college football to dinosaurs after watching a Netflix documentary, saying programs must 'adapt or die' as the sport undergoes dramatic changes with player transfers and NIL deals." },
    { documentId: "vhla40ptoas4cx7dndzknnj2", content: "UConn coach Dan Hurley downplayed his unusual interaction with an official at the end of the historic NCAA tournament win over Duke, jokingly saying he thought the referee was approaching for a 'chest-bump.'" },
    { documentId: "vnmgoqyzd0mz06415cnvld42", content: "Mark Cuban publicly expressed regret over selling the Dallas Mavericks to Miriam Adelson and Patrick Dumont, as the divide between the former owner and new ownership continues to deepen." },
    { documentId: "k24t4je8mbh1drvuwx60ycjt", content: "New England Patriots coach Mike Vrabel didn't dismiss trade speculation surrounding Eagles wide receiver A.J. Brown, fueling rumors that the Patriots could be a potential landing spot in a trade deal." },
    { documentId: "cpjm6mi0y3liezlfvbjd9por", content: "A quadruple amputee professional cornhole player, Dayton Webber, allegedly shot and killed a passenger in his Tesla after an argument over 'drugs, guns, and a woman' in southern Maryland, according to court documents." },
    { documentId: "o0309kgvt8h8cvlhsypja35a", content: "The 2026 Pain Index ranks the most devastating losses in March Madness history, examining where Duke's latest tournament exit fits among the most heartbreaking defeats in college basketball." },
    { documentId: "b6ltt7asi7mpcmwoaqti6356", content: "Turkey ended a 24-year wait to qualify for the World Cup by beating Kosovo 1-0, while Sweden also booked their spot. Kosovo and Poland were eliminated in the European qualifying playoffs." },
    { documentId: "j82y3ceh4431vhegfhq6juaz", content: "An investigation into emotional abuse in college sports reveals widespread patterns of coaches crossing the line from tough coaching into harmful psychological manipulation. The report examines how institutional cultures enable abusive behavior to persist." },
    // === ENTERTAINMENT ===
    { documentId: "t9qmoof7n65eo7we0abnm3ag", content: "K-pop group Blackpink made history as the first Asian act to headline Coachella, performing in Korean hanboks that paid homage to their cultural heritage before a crowd of over 125,000 people." },
    { documentId: "l9j6syuejln3vdoxbfuicmjl", content: "Cinematographer Greig Fraser describes 'Project Hail Mary' as his most challenging film ever, explaining how he created a practical sun effect to light the tunnel scene. The film is based on Andy Weir's novel and stars Ryan Gosling." },
    { documentId: "r9kbjopd13cr5j98kqejzsml", content: "Comic actor Joel McHale showcased surprising dramatic versatility in 'Scream 7,' playing a doting dad, undercover lover, and action star without going for laughs — the sixth sequel in the franchise that crossed $200 million globally." },
    { documentId: "uyh7c8v5umi6xfv264ubdlhh", content: "Moscow's latest entertainment craze is a war game where players race to find nuclear launch codes inside a Soviet-era themed bunker, reflecting broader anxieties about nuclear tensions while Russian officials stage mass nuclear drills." },
    { documentId: "glqtw62r7qw33ejw0wysvtxf", content: "Actor Sam Worthington says the 'Avatar' franchise, which has grossed $6.7 billion across three films, can take more creative risks than Marvel movies because there's less studio and fan pressure on the production process." },
    { documentId: "dzxdzyz3atg1zmiyzesv6a2q", content: "Amazon and Mattel are launching 'Masters of the Universe: Legends Unite,' a new game debuting on Amazon Luna on June 5 to coincide with the theatrical release of the Masters of the Universe movie from Amazon MGM Studios." },
    { documentId: "r45hnfo6b70funflqhm6zdzn", content: "A federal judge ruled that President Trump's executive order to end funding for PBS and NPR violated the First Amendment. The ruling found the order was an illegal attempt to punish public media organizations for their editorial content." },
    { documentId: "e7axuoe5l7tjgr7l2lw8fr0x", content: "Letterboxd is partnering with distributor Black Bear to bring its popular 'Four Favorites' screening format to theaters nationwide, tied to the release of the thriller 'Tuner' starring Leo Woodhall." },
    { documentId: "k5vwfo9fwwax2q4r9i5zjl6n", content: "Universal Music Latin America announced three key executive appointments under CEO Jesús López, restructuring its leadership team for the Latin Entertainment, digital, and creative divisions across the region." },
    { documentId: "gck15u4hc9jr55j5e149d9z1", content: "The Super Mario Galaxy Movie sequel is criticized as a frenetic, threadbare adventure overly reliant on video-game Easter eggs. The film introduces Yoshi voiced by Donald Glover and Luma characters, but lacks the narrative substance of its predecessor." },
    { documentId: "s29gwj3y9o5bo8g6hx0r87q8", content: "The Simpsons partnered with Lids for an MLB-themed New Era hat collection featuring five capsules, launching to celebrate the 2026 baseball season with Springfield-inspired designs." },
    { documentId: "if9nquwyqd9dvm2o9zlzjdy8", content: "Fuse Media and Billboard are launching Billboard Español TV, a streaming channel featuring Spanish-language programming covering music and culture for Latino audiences across the US and internationally." },
    // === SCIENCE ===
    { documentId: "t6hf2grcw6achzkr07fytdn5", content: "Scientists identified a brain circuit that controls growth hormone release during deep non-REM sleep, explaining why poor sleep leads to lower growth hormone levels. The discovery could lead to treatments for muscle loss, fat accumulation, and cognitive decline related to sleep deprivation." },
    { documentId: "puol04jhebt21pozydxlexot", content: "NASA's James Webb Space Telescope detected an unusually energetic gamma-ray burst (GRB 250702B) that defies known physics. The burst, which occurs when a massive star collapses into a black hole, exhibited characteristics that don't match existing theoretical models." },
    { documentId: "tpivn8a8uzcqf4jc6mzaym1o", content: "A new study found that simple physical therapies like exercise and manual treatment outperform anti-inflammatory drugs for knee osteoarthritis pain relief, with fewer side effects. The findings could shift treatment guidelines for the millions of older adults affected." },
    { documentId: "lrq2ke5wlptb832ixm3ib2b1", content: "Researchers discovered that supermassive black holes in one galaxy can suppress star formation in neighboring galaxies, challenging the traditional view that galaxies evolve independently due to their vast distances apart." },
    { documentId: "qsrr9b8737rnh3h20fmu8b4z", content: "A powerful cholesterol-lowering drug reduced heart attack risk by 31% in patients who had not yet developed cardiovascular disease, demonstrating benefits of intensive cholesterol treatment for prevention rather than just treatment of existing conditions." },
    { documentId: "x4vzpjc3hipwj4siw3um3loz", content: "Scientists at the University of Waterloo proposed a new theory for how the Big Bang may have occurred, combining gravity with quantum physics in a novel way that could resolve long-standing incompatibilities between Einstein's general relativity and quantum mechanics." },
    { documentId: "p51llo7qc10g79m1a6r11kko", content: "Researchers identified an overlooked hormone that may explain why nearly 10 million Americans have resistant hypertension — blood pressure that stays high despite taking three or more medications. The finding could lead to more targeted treatments." },
    { documentId: "gawg38iff8ma8bwciefwzz34", content: "Scientists found that some dinosaurs like Uberabatitan could grow to enormous sizes but eventually reached a biological limit. Even smaller sauropods could reach 26 meters in length, making them the largest known dinosaurs from Brazil." },
    { documentId: "qvdl69lggmh1xct0gowkyyds", content: "Scientists discovered that liquids can snap like solids when stretched, revealing that viscosity plays a much larger role in mechanical behavior than previously believed. The finding has implications for hydraulics, 3D printing, and understanding blood flow." },
    { documentId: "ct2x743d71zdk0aaii57ried", content: "Research analyzing data from nearly 96,000 people found that just a few minutes of vigorous physical activity per day can significantly lower the risk of eight major diseases. Even brief moments of higher-intensity effort showed measurable health benefits." },
    { documentId: "mej01w22uabwg09tqck7vt3i", content: "Scientists found that Old Masters like Leonardo da Vinci, Botticelli, and Rembrandt likely used egg yolk proteins as a secret ingredient in their oil paintings, which helped create distinctive textures and lasting durability in their masterworks." },
    // === WORLD ===
    { documentId: "s9d5wvd58yjyk8qmoijj6obo", content: "Reports and witnesses reveal that Iran is deploying children in security roles during the ongoing war, with members of the Basij volunteer militia including minors. The practice raises serious concerns about child welfare violations under international law." },
    { documentId: "oiyvyk97w5ow8gui8979oha2", content: "Israel announced it will maintain military control over part of southern Lebanon even after the war with Hezbollah ends, establishing a 'security buffer zone' stretching dozens of kilometers into Lebanese territory." },
    { documentId: "qgptqan84drc2z01k7q9pa3b", content: "US freelance journalist Shelly Kittleson, who has covered conflicts in Afghanistan, Iraq, and Syria, was kidnapped in Baghdad. The circumstances of her abduction remain unclear." },
    { documentId: "ksezcdyvmi27cr8ymiavei2k", content: "UN peacekeepers were killed by a roadside explosion in Lebanon, according to an initial report. The UN's peacekeeping force (UNIFIL) patrols the de facto border between Lebanon and Israel." },
    { documentId: "sr32tdccwpmncjw038n6jpvz", content: "A US federal judge temporarily halted the construction of President Trump's planned White House ballroom, the latest in a series of judicial setbacks for the administration's agenda." },
    { documentId: "hccg0wic14tw69zbojxtvp3w", content: "An Italian Christmas meal tragedy has turned into a murder inquiry after doctors initially believed a woman and her daughter had food poisoning. Investigators now suspect foul play in the case." },
    { documentId: "j1lk3vfbotv3mjfap068cet2", content: "A wolf attacked and bit a woman on a busy Hamburg shopping street in Germany, shocking passersby. The rare urban wolf attack highlights growing concerns about wolf populations expanding into populated areas across Europe." },
    { documentId: "ee8ubrcruy7c2m16sujz501c", content: "China has banned the practice of storing cremated remains in empty high-rise apartments known as 'bone ash apartments,' which had become popular as cemetery costs soared. The crackdown targets a workaround that emerged due to limited and expensive traditional burial space." },
    { documentId: "n8iz840isgqugo5qvne1g9a2", content: "The Eurovision Song Contest announced its first-ever Asia edition, expanding the world's longest-running international music competition beyond its traditional European base into new markets." },
    { documentId: "zra5ddtrhqooekyth6vihyre", content: "Lake Powell, the second-largest US reservoir, has lost nearly 7% of its storage capacity since 1963 due to sediment buildup, compounding the water crisis caused by an intense multiyear drought in the American Southwest." },
    { documentId: "f27grhdwtu6exm2e4juimsil", content: "Experts say big-box retailers like Walmart and Target could significantly reduce emissions and save millions by installing solar panels on their vast rooftops, but most aren't doing it due to upfront costs and complex permitting processes." },
    { documentId: "ou6k81qze4a49odewl7noo6p", content: "A global air quality report found that average annual air pollution in every country exceeded WHO guidelines in 2021, with 97% of cities failing to meet standards. The findings underscore the growing global health threat from poor air quality." },
    { documentId: "tzlaryhryfmqk5mjqsp20mwm", content: "A Russia-flagged oil tanker docked in Cuba, ending a near-total blockade. The US allowed the vessel to proceed despite an ongoing energy blockade that had left the island nation facing critical fuel shortages." },
    { documentId: "cvkj11pqv5ov8yqwcubwo500", content: "Cuba's tourism workers are reeling from the US oil blockade, with taxi drivers and hospitality staff struggling as visitor numbers plummet. The energy shortage has devastated the island's tourism-dependent economy." },
    { documentId: "zo2ii0dsmhqtynmxlfoc3c8s", content: "The UN passed a resolution declaring slavery the gravest crime against humanity, with only Argentina, Israel, and the US voting against it. Critics argue the resolution lacks enforcement mechanisms and doesn't go far enough to address the ongoing legacy of slavery." },
    // === POLITICS ===
    { documentId: "yd544wk3z7i3hkag1kx2ukl4", content: "Golf legend Tiger Woods pleaded not guilty to DUI charges in Florida after a car crash where opioid pain pills were found at the scene. He waived his arraignment hearing appearance and entered the plea through the court's online system." },
    { documentId: "uzp3uk97n7qtk2bsus570098", content: "The US Supreme Court ruled 8-1 against Colorado's ban on LGBTQ child 'conversion therapy,' with two liberal justices joining the six conservative justices. The decision overturned a state law banning the discredited and harmful practice." },
    { documentId: "cs9i6u6toogi0przuut8nmb1", content: "A Russian tanker carrying 730,000 barrels of oil reached Cuba, the first oil delivery in three months amid a critical energy shortage. The Trump administration allowed the vessel to proceed despite the ongoing US energy blockade." },
    { documentId: "bdyxj4hwrq1m4xqiptecc2u8", content: "Three former FBI agents filed a class-action lawsuit alleging they were wrongfully fired in retaliation for their work investigating President Trump. The suit is the latest legal challenge against efforts to purge federal law enforcement staff." },
    // === HEALTH ===
    { documentId: "ifc5z8dstfoudjk41m36xmq3", content: "The wellness community is closely watching RFK Jr.'s promised regulatory changes on synthetic peptides, which are gaining popularity as treatments despite most not being tested for safety in humans. The outcome could reshape access to these compounds." },
    { documentId: "uc2qda582g4lwrsh8sb8ryk8", content: "Advocates argue that babies are being overlooked in the legal battle over birthright citizenship, as the focus remains on constitutional principles rather than the practical impact on newborns who may be denied citizenship documentation." },
    { documentId: "un6jpa8f90sxxsre6ls7kbyv", content: "The CDC currently lacks a director, raising questions about the agency's ability to respond to public health emergencies. The leadership vacuum comes at a time when the nation faces ongoing threats from infectious diseases and other health crises." },
    { documentId: "rnbfc0iqk3a4996blaz62h15", content: "Mexico is conducting a massive measles vaccination campaign, but public trust remains a challenge. Health workers are navigating vaccine hesitancy while trying to prevent outbreaks in a country where vaccination rates have declined." },
    { documentId: "m3po82gpfane8khcixd2ez9u", content: "New research identifies specific design features that make social media more addictive for teens and suggests concrete changes companies could implement. The findings provide a roadmap for platforms to reduce harmful engagement patterns among young users." },
    { documentId: "jjkeq0zngsp2b5hr3glkvrbx", content: "A guide to personalizing protein intake based on individual needs, explaining how factors like age, activity level, and health goals affect optimal protein consumption. The article debunks common myths about protein requirements." },
    { documentId: "x7hdoz42hylqsbksbvu7n79f", content: "A practical guide to navigating the complex landscape of drug discounts, comparing manufacturer coupons, pharmacy discount programs, and insurance copays to help patients find the lowest price for their medications." },
    { documentId: "pen4ox571nfgj645xqzke2cv", content: "A guide for family caregivers on planning for the future, addressing the critical question 'What if I die first?' It covers legal documents, financial planning, and finding backup care arrangements for loved ones with disabilities." },
    { documentId: "dffd93nk25s1f8u3qnilm24p", content: "A woman whose father had dementia created a comprehensive guide for family caregivers, drawing on her personal experience navigating the challenges of Alzheimer's care. The resource covers practical and emotional aspects of caregiving." },
    // === EDUCATION ===
    { documentId: "tunpp9i8obho4kw9avlsvi7i", content: "Education researchers face a difficult choice between speaking out on politically charged issues and protecting their careers. The pressure to publicly advocate or remain silent creates a high-stakes dilemma with professional consequences either way." },
    { documentId: "d0c7rb34eg6f00vo4ppotnbq", content: "ICE immigration enforcement operations near schools are causing deep psychological trauma for students, leading to declining enrollment and diminishing job prospects. Educators nationwide report that fear of deportation is disrupting learning environments." },
    { documentId: "pns850fn90galigt6i4kcbku", content: "AI-powered college counseling platforms are providing on-demand guidance to students who lack access to traditional counselors. The technology aims to democratize college admissions advice, though questions remain about AI's ability to replicate human mentorship." },
    { documentId: "vnd1i5xhgpv5mnc4e2bjf2ny", content: "Winning a prestigious academic award like a Fulbright can be life-transforming for working-class students in ways that go beyond the resume boost, opening doors to networks and opportunities that were previously inaccessible." },
    { documentId: "qtfzky5imhd4ks4qph9q6e0n", content: "Child care centers are turning to retirees to help fill persistent staffing shortages. The intergenerational approach brings experienced adults into early childhood settings while providing meaningful engagement for older volunteers." },
    { documentId: "hciwtw474luibvshbw1hpsly", content: "Readers responded passionately to a story about screen time in schools, with opinions divided on whether devices help or hinder learning. The feedback highlights the ongoing tension between educational technology adoption and traditional teaching methods." },
    { documentId: "ypp0cy4yv34z4pwrt4qcpydj", content: "An investigation examines whether New York state wasted $10 million on a reading instruction program that research suggests doesn't work. The case raises broader questions about how education policy decisions are made and evaluated." },
    { documentId: "h6mde9ymzxn1604r50oh94sx", content: "AI is creating a 'hivemind' effect where student essays increasingly sound alike, as students using AI tools converge on similar phrasing and structures. The phenomenon challenges educators to rethink how they assess original thinking." },
    { documentId: "lwriglt5bjp7ce912wfrzyib", content: "School districts that invested in green building practices are seeing significant cost savings on energy and maintenance. In Warren County, Kentucky, the district saved substantially by implementing energy-efficient designs in school facilities." },
    { documentId: "lfdvk4mt06n9rzo40ci8e7ye", content: "A Minneapolis child care center navigated a surge in ICE immigration enforcement activity in its neighborhood, continuing to serve families despite the climate of fear. The center's story illustrates the resilience of community institutions under pressure." },
    { documentId: "inv2rzx0ra9a2ugm6xti8pi3", content: "A potential Supreme Court decision on birthright citizenship could have far-reaching implications for education access, affecting which students qualify for public schooling and financial aid programs across the United States." },
    { documentId: "c991xp7be3sfawty8cy1fr2v", content: "Federal student loan management is being transferred from the Education Department to the Treasury Department, further shrinking an agency already under pressure from the administration's cost-cutting agenda." },
    { documentId: "jhlaffwcjv11oxd17qn86388", content: "A new graphic novel tells the story of a school book ban in Chicago, inspired by real events. The tale explores themes of censorship, intellectual freedom, and the power of literature in education." },
    { documentId: "krbasita5igboqn93jfsn1f5", content: "A Texas high school swim team organized a fundraiser for a hospitalized school custodian, demonstrating the close-knit community bonds that form in schools between students and support staff." },
    { documentId: "k4sdd0kkgg5jwru6qz5d8jdq", content: "California teachers are revising lesson plans about labor leader Cesar Chavez following abuse allegations that have complicated his legacy. Educators must balance teaching about his significant contributions to labor rights while addressing the new revelations." },
    { documentId: "gib8prvmeujq04qbepmeuq4b", content: "The depleted Education Department is moving out of its headquarters as the Energy Department takes over the building. The relocation symbolizes the shrinking role of the federal education agency under the current administration." },
    { documentId: "mncuu83xxvuj3os3lkmdjwjp", content: "Cursive handwriting is making a comeback in schools as states reintroduce it into curricula, but debate continues over whether the time spent on cursive could be better used for other skills in an increasingly digital world." },
    { documentId: "eznwlim824nsmr0czbubwk30", content: "A federal watchdog reports that key oversight mechanisms ensuring the accuracy of student loan records have stopped functioning, putting millions of borrowers at risk of errors in their loan accounts." },
    { documentId: "y2swp9qai00u6fyf9vgf3odi", content: "Colleges are developing new programs to reconnect with students who left before earning degrees, offering flexible pathways to completion. The effort targets the estimated 40 million Americans with some college credit but no degree." },
    { documentId: "gdqm3mav8lj8bf5trh181tuf", content: "Teachers across California are considering work stoppages amid disputes over pay, class sizes, and working conditions. The potential actions reflect broader frustration among educators facing resource constraints and growing demands." },
    // === ENVIRONMENT ===
    { documentId: "zlld6pa4ani2wsqrklrytsrz", content: "Arctic sea ice hit a record low for the second year running this winter, with extent peaking at just 14.29 million square kilometers. Scientists call the trend 'very alarming' as it indicates accelerating polar ice loss." },
    { documentId: "jsqa2rvh4bu5tya381zyhw9d", content: "Extreme weather events drove $107 billion in insured losses in 2025, with the Los Angeles wildfires alone causing a record $40 billion in fire-related insured losses. Storms and wildfires were the primary drivers of the massive insurance payouts." },
    { documentId: "qkob7ujyprqy0edi5m3oi7lk", content: "This week's climate briefing covers the Iran war's delayed ultimatum over the Strait of Hormuz, debunking North Sea oil myths, India's new climate plan, and efforts to integrate Indigenous knowledge into IPCC reports." },
    { documentId: "abg26gld0abmu5sn4qnmfcp8", content: "India set a new target to reduce emissions intensity by 47% below 2005 levels by 2035 in its updated Paris Agreement pledge. While welcomed, some analysts say the targets are easily achievable given India's current progress on renewable energy." },
    { documentId: "rai7mysh7zyce4fciwzt1nh4", content: "Low-level cloud cover has been declining for two decades, allowing more sunlight to reach Earth's surface and amplifying global warming. The research raises concerns about a feedback loop that could accelerate climate change beyond current projections." },
    { documentId: "x7hop7f4jxoua7cvuglpiqi5", content: "A factcheck debunks nine false or misleading myths about North Sea oil and gas that have gained traction amid the Iran war energy crisis, as politicians and media push for more drilling licenses." },
    { documentId: "k5blu0bje5fush3b9umw10pm", content: "A roundup of climate and land-use developments including stalled seabed mining negotiations, a new blueprint for sustainable land use, and the impacts of the Iran war on India's economy and energy markets." },
    { documentId: "pcdo01h6uhu441xf9sm4rnxa", content: "Analysis reveals the UK is effectively halving its climate finance for developing countries when accounting changes and inflation are factored in, despite the government's announced £6 billion commitment." },
    { documentId: "klsd9j8uto7sgbkabxq43cn7", content: "India's CO2 emissions grew by just 0.7% in 2025, the slowest rate in over two decades and a sharp decline from the 4-11% growth in preceding years. The slowdown reflects India's expanding renewable energy capacity." },
    { documentId: "g1yq5468jar40m3clbut15rh", content: "Research published in Nature warns that limiting warming to 2°C may not prevent extreme climate impacts like drought in agricultural regions and flooding in populated areas. The study suggests even the Paris Agreement's goals may be insufficient." },
    { documentId: "u278husr15tuuueiy3tibv9k", content: "46 nations including major oil producers Canada, Australia, Brazil, and Norway will attend a fossil fuel phase-out summit in Santa Marta, though the world's biggest producers remain absent from the initiative." },
    { documentId: "zz0kpgxo8l1yexbkmvoff49n", content: "Small island nations are fighting to preserve cultural heritage sites threatened by rising seas and extreme weather. Communities are developing innovative preservation strategies while advocating for stronger global climate action." },
    { documentId: "ltvvxgszigz2lnevv3avi55o", content: "As the Middle East conflict disrupts global energy markets, Barbados charts a practical path for small island states to build energy resilience through renewable sources, reducing dependence on volatile fossil fuel imports." },
    { documentId: "muuk500e5q1kmc5dbxaa3q9s", content: "India announced new 2035 targets for green electricity generation and emissions intensity reduction. While most analysts praised the goals, some noted they are conservative and easily achievable given India's rapid renewable energy expansion." },
    { documentId: "od7d7kvcvflon41zdbj8yw7v", content: "Madagascar's Rindra Rabarinirinarison takes the helm of the troubled Global Center on Adaptation, promising to prioritize fundraising and refocus the organization on helping developing countries build climate resilience." },
    { documentId: "r877ocbdqgiiwgsvrw7jvmo0", content: "The UN's Green Climate Fund selected locations for five new hubs in developing countries to improve access to climate finance. The new offices aim to boost local capacity for securing and managing climate adaptation funding." },
    { documentId: "igv82btxnq7eaxo3snpna3vc", content: "Ugandan farmers are using a British court to try to block the East African crude oil pipeline, arguing that a UK-based entity linked to the project should be held accountable for environmental and social impacts." },
    { documentId: "yja6ztnk6ahar59dbql0ds38", content: "Dutch startup Ore Energy is developing iron-air batteries that could help solve Europe's energy storage gap. The long-duration batteries use rust-based chemistry and could provide affordable grid-scale storage to complement renewable energy." },
    { documentId: "vm8h0qofzbp5uigidjkvsbin", content: "Colombia's environment minister suggested the Iran war could accelerate the global push to phase out fossil fuels, as energy supply disruptions highlight the risks of continued oil dependence." },
    { documentId: "rzrnjvesll0h9p08hkaw4r4z", content: "Early warning systems installed across Central Asia are saving lives by giving communities advance notice of floods, landslides, and other natural disasters. Community involvement in monitoring and response has been key to their effectiveness." },
    // === FINANCE ===
    { documentId: "yqpcb47hhpc5uhqg92beeaik", content: "Bitcoin has tumbled 22% in Q1 2026, following a 25% drop in Q4 2025, marking a historic stretch of underperformance against traditional stock markets." },
    { documentId: "imwrgf1ijtgvw36u5ltrer2s", content: "A WisdomTree executive argues that the Clarity Act is not a gatekeeper for crypto innovation, saying the industry can proceed under existing SEC rules while the legislation faces Congressional debate." },
    { documentId: "qcbnlao3eyxs77v552qsfl2r", content: "Google's quantum computing research potentially threatens bitcoin's cryptographic foundation, putting the entire supply at risk. Experts warn the post-quantum transition in digital security can no longer be postponed." },
    { documentId: "n1s7cjna8o77fs7y9batlg6k", content: "Cardano founder Charles Hoskinson criticizes the CLARITY Act, warning it could be weaponized by future lawmakers. He says the legislation's narrow US-only approach risks stifling new crypto projects while benefiting established players." },
    { documentId: "sotvtd9kgy2zglw8ti3vvgqf", content: "Despite recent regulatory progress in crypto, financial privacy remains an area needing clear rules, according to industry experts calling for comprehensive legislation to address privacy concerns in digital transactions." },
    { documentId: "yy1b68enmngr80www5z4u642", content: "Bitfarms is pivoting from bitcoin mining to AI by actively selling its bitcoin holdings and redeploying capital into AI-focused data centers, targeting zero bitcoin on its balance sheet as part of a broader business transformation." },
    { documentId: "fuc7vytg844qgx4ql6kmuwr9", content: "Bitcoin and stocks rose while oil prices slid after reports that Iran's President Pezeshkian expressed willingness to end the conflict if Iran receives security guarantees, easing market tensions." },
    { documentId: "ndy66c2oyby3zgz8x2xb2lw3", content: "A consortium of 12 European banks is racing to put the euro on blockchain to compete with dollar dominance in crypto markets, aiming to prevent 'digital dollarization' of European financial systems." },
    { documentId: "dkr97x1jjxmnock2huck3i2s", content: "Mercado Libre is shutting down Mercado Coin starting April 17, ending its loyalty-driven crypto experiment. Users can sell, spend, or have their tokens converted to local currency before the deadline." },
    { documentId: "xw2lhqc0hhh4tjpt0dx54uk6", content: "Oil prices soared 60% in March after Tehran closed the Strait of Hormuz in response to US-Israeli strikes, triggering the biggest crude price rally in decades and choking global energy supplies." },
    { documentId: "pxefd6abdnas5c8a7d54wmfk", content: "Iran's cyber operatives have launched a series of attacks on Israeli and US targets, seeking to sow fear and extract intelligence as the physical conflict extends into cyberspace." },
    { documentId: "ybq3625pveos4kw9yu3rlhtx", content: "Politicians' bullish rhetoric about 'unleashing' AI technology is badly out of touch with public sentiment, as many voters express concerns about job displacement, privacy, and the pace of AI deployment." },
    { documentId: "clawz4vhhmixm42so2suhtzl", content: "President Trump faces declining poll numbers as his trade and immigration agendas encounter mounting judicial resistance, with multiple courts blocking key policy initiatives." },
    { documentId: "mh57eogc4rq7nxqmo3ujp2iq", content: "Israeli Defence Minister Israel Katz announced plans to demolish all houses in Lebanese border villages and establish a 'security control' zone stretching dozens of kilometres into Lebanon." },
];

async function batchUpdate() {
    const headers = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_TOKEN}`,
    };

    console.log(`Updating ${updates.length} articles on ${STRAPI_URL}...\n`);

    let success = 0;
    let failed = 0;

    for (const item of updates) {
        try {
            const res = await fetch(`${STRAPI_URL}/api/news-articles/${item.documentId}`, {
                method: 'PUT',
                headers,
                body: JSON.stringify({ data: { content: item.content } }),
            });

            if (res.ok) {
                success++;
                process.stdout.write(`\r✓ Updated ${success}/${updates.length}`);
            } else {
                const err = await res.json();
                failed++;
                console.log(`\n✗ Failed [${item.documentId}]: ${err.error?.message || res.status}`);
            }
        } catch (e) {
            failed++;
            console.log(`\n✗ Error [${item.documentId}]: ${e.message}`);
        }
    }

    console.log(`\n\n============================================================`);
    console.log(`  Done: ${success} updated, ${failed} failed`);
    console.log(`============================================================`);
}

batchUpdate();
