/**
 * News Sources Configuration
 * All RSS feed and web scraping sources
 */

module.exports = {
    // RSS Feed Sources
    rss: [
        {
            id: 'techcrunch',
            name: 'TechCrunch',
            category: 'Technology',
            rssUrl: 'https://techcrunch.com/feed/',
            website: 'https://techcrunch.com',
            description: 'Technology news and startup insights',
            contentSelector: 'div.entry-content, div.article-content',
        },
        {
            id: 'bbc-tech',
            name: 'BBC News',
            category: 'Technology',
            rssUrl: 'http://feeds.bbci.co.uk/news/technology/rss.xml',
            website: 'https://bbc.com/news',
            description: 'BBC Technology News',
            contentSelector: 'article div[data-component="text-block"], main article',
        },
        {
            id: 'cnn-tech',
            name: 'CNN',
            category: 'Technology',
            rssUrl: 'http://rss.cnn.com/rss/edition_technology.rss',
            website: 'https://cnn.com',
            description: 'CNN Technology News',
            contentSelector: 'div.article__content, div.article__main',
        },
        {
            id: 'cnbc',
            name: 'CNBC',
            category: 'Business',
            rssUrl: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10001147',
            website: 'https://cnbc.com',
            description: 'CNBC Business & Finance News',
            contentSelector: 'div.ArticleBody-articleBody, div.RenderKeyPoints-list',
        },
        {
            id: 'espn',
            name: 'ESPN',
            category: 'Sports',
            rssUrl: 'http://www.espn.com/espn/rss/news',
            website: 'https://espn.com',
            description: 'ESPN Sports News',
            contentSelector: 'div.article-body',
        },
        {
            id: 'variety',
            name: 'Variety',
            category: 'Entertainment',
            rssUrl: 'https://variety.com/feed/',
            website: 'https://variety.com',
            description: 'Entertainment News',
            contentSelector: 'div.a-content, div.entry-content',
        },
        {
            id: 'npr-health',
            name: 'NPR Health',
            category: 'Health',
            rssUrl: 'https://feeds.npr.org/1128/rss.xml',
            website: 'https://npr.org/sections/health',
            description: 'NPR Health News',
            contentSelector: 'div.storytext, article.story',
        },
        {
            id: 'science-daily',
            name: 'Science Daily',
            category: 'Science',
            rssUrl: 'https://www.sciencedaily.com/rss/all.xml',
            website: 'https://sciencedaily.com',
            description: 'Science Research News',
            contentSelector: 'div#text',
        },
        {
            id: 'bbc-world',
            name: 'BBC World',
            category: 'World',
            rssUrl: 'http://feeds.bbci.co.uk/news/world/rss.xml',
            website: 'https://bbc.com/news/world',
            description: 'BBC World News',
            contentSelector: 'article div[data-component="text-block"], main article',
        },
        {
            id: 'cnn-world',
            name: 'CNN World',
            category: 'World',
            rssUrl: 'http://rss.cnn.com/rss/edition_world.rss',
            website: 'https://cnn.com/world',
            description: 'CNN International News',
            contentSelector: 'div.article__content, div.article__main',
        },
        {
            id: 'al-jazeera',
            name: 'Al Jazeera',
            category: 'Politics',
            rssUrl: 'https://www.aljazeera.com/xml/rss/all.xml',
            website: 'https://aljazeera.com',
            description: 'International News and Politics',
            contentSelector: 'div.wysiwyg--all-content, div.article-details',
        },
        // Education
        {
            id: 'npr-education',
            name: 'NPR Education',
            category: 'Education',
            rssUrl: 'https://feeds.npr.org/1013/rss.xml',
            website: 'https://npr.org/sections/education',
            description: 'NPR Education News',
            contentSelector: 'div.storytext, article.story',
        },
        {
            id: 'the-hechinger-report',
            name: 'The Hechinger Report',
            category: 'Education',
            rssUrl: 'https://hechingerreport.org/feed/',
            website: 'https://hechingerreport.org',
            description: 'Education News and Analysis',
            contentSelector: 'div.entry-content, article',
        },
        // Environment / Climate
        {
            id: 'carbon-brief',
            name: 'Carbon Brief',
            category: 'Environment',
            rssUrl: 'https://www.carbonbrief.org/feed/',
            website: 'https://carbonbrief.org',
            description: 'Climate Science and Energy Policy',
            contentSelector: 'div.entry-content, article',
        },
        {
            id: 'climate-home',
            name: 'Climate Home News',
            category: 'Environment',
            rssUrl: 'https://www.climatechangenews.com/feed/',
            website: 'https://climatechangenews.com',
            description: 'Climate Change and Environment News',
            contentSelector: 'div.entry-content, article',
        },
        // Finance / Crypto
        {
            id: 'coindesk',
            name: 'CoinDesk',
            category: 'Finance',
            rssUrl: 'https://www.coindesk.com/arc/outboundfeeds/rss/',
            website: 'https://coindesk.com',
            description: 'Crypto and Digital Finance News',
            contentSelector: 'div.article-content, div.at-content-wrapper',
        },
        {
            id: 'financial-times',
            name: 'Financial Times',
            category: 'Finance',
            rssUrl: 'https://www.ft.com/rss/home',
            website: 'https://ft.com',
            description: 'Global Finance and Markets News',
            contentSelector: 'div.article__content-body, article',
        },
    ],

    // Web Scraping Sources
    websites: [
        {
            id: 'techcrunch',
            name: 'TechCrunch',
            category: 'Technology',
            baseUrl: 'https://techcrunch.com',
            articleListUrl: 'https://techcrunch.com',
            selectors: {
                article: 'article.post-block',
                title: 'h2.post-block__title a',
                link: 'h2.post-block__title a',
                summary: 'div.post-block__content',
                image: 'img.post-block__featured__image',
                time: 'time.post-block__time',
                author: 'span.author__name',
            },
        },
        {
            id: 'bbc',
            name: 'BBC News',
            category: 'Technology',
            baseUrl: 'https://bbc.com',
            articleListUrl: 'https://bbc.com/news/technology',
            selectors: {
                article: 'article[data-testid="card-text-wrapper"]',
                title: 'h3[data-testid="card-headline"]',
                link: 'a[data-testid="internal-link"]',
                summary: 'p[data-testid="card-description"]',
                image: 'img[data-testid="card-media"]',
                time: 'time',
                author: '[data-testid="byline-names"]',
            },
        },
        {
            id: 'cnn',
            name: 'CNN',
            category: 'Business',
            baseUrl: 'https://cnn.com',
            articleListUrl: 'https://cnn.com/business',
            selectors: {
                article: 'article.container_lead-plus-headlines__item',
                title: 'h3.container_lead-plus-headlines__title a',
                link: 'h3.container_lead-plus-headlines__title a',
                summary: 'p.container_lead-plus-headlines__description',
                image: 'img.container_lead-plus-headlines__media',
                time: 'span.card__timestamp',
                author: 'span.card__byline',
            },
        },
        {
            id: 'cnbc',
            name: 'CNBC',
            category: 'Business',
            baseUrl: 'https://cnbc.com',
            articleListUrl: 'https://cnbc.com/business',
            selectors: {
                article: 'div.Card-titleContainer',
                title: 'a.Card-title',
                link: 'a.Card-title',
                summary: 'div.Card-description',
                image: 'img.Card-mediaImage',
                time: 'time',
                author: 'span.Card-byline',
            },
        },
        {
            id: 'espn',
            name: 'ESPN',
            category: 'Sports',
            baseUrl: 'https://espn.com',
            articleListUrl: 'https://espn.com',
            selectors: {
                article: 'article.article',
                title: 'h2.ArticleHeader h2 a',
                link: 'h2.ArticleHeader h2 a',
                summary: 'p.ArticleSummary p',
                image: 'img.ArticleHeader__image',
                time: 'time.ArticleHeader__timestamp',
                author: 'span.ArticleHeader__byline',
            },
        },
        {
            id: 'variety',
            name: 'Variety',
            category: 'Entertainment',
            baseUrl: 'https://variety.com',
            articleListUrl: 'https://variety.com',
            selectors: {
                article: 'article.c-post',
                title: 'h4.c-post__title a',
                link: 'h4.c-post__title a',
                summary: 'div.c-post__excerpt',
                image: 'img.c-post__thumbnail',
                time: 'time.c-timestamp',
                author: 'span.c-byline__author',
            },
        },
        {
            id: 'npr-health',
            name: 'NPR Health',
            category: 'Health',
            baseUrl: 'https://npr.org',
            articleListUrl: 'https://npr.org/sections/health',
            selectors: {
                article: 'article.item',
                title: 'h2.title a',
                link: 'h2.title a',
                summary: 'p.teaser',
                image: 'img.imagewrap',
                time: 'time',
                author: 'span.byline',
            },
        },
        {
            id: 'sciencedaily',
            name: 'Science Daily',
            category: 'Science',
            baseUrl: 'https://sciencedaily.com',
            articleListUrl: 'https://sciencedaily.com/news/all/',
            selectors: {
                article: 'div.story',
                title: 'a.storylink',
                link: 'a.storylink',
                summary: 'p.storytext',
                image: null,
                time: 'small.storydate',
                author: null,
            },
        },
    ],

    // API Sources (require API keys)
    apis: [
        {
            id: 'newsapi',
            name: 'NewsAPI.org',
            apiKey: process.env.NEWSAPI_KEY,
            baseUrl: 'https://newsapi.org/v2',
            categories: ['technology', 'business', 'sports', 'entertainment', 'health', 'science', 'education'],
        },
        {
            id: 'guardian',
            name: 'The Guardian',
            apiKey: process.env.GUARDIAN_API_KEY,
            baseUrl: 'https://content.guardianapis.com',
            categories: ['technology', 'business', 'sport', 'culture', 'science'],
        },
        {
            id: 'nytimes',
            name: 'The New York Times',
            apiKey: process.env.NYTIMES_API_KEY,
            baseUrl: 'https://api.nytimes.com/svc/topstories/v2',
            categories: ['home', 'technology', 'business', 'sports', 'science'],
        },
    ],
};
